language: node_js

node_js:
- '0.10'

before_script:
- npm install -g grunt-cli
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

script:
- grunt --stack travis

env:
  global:
  - secure: Fl/qjPMV8zffsBb6XEyGViBL3hFD5zYbIkZtNdbVB9ks4bVqyexeDBQlQk/sMC9CDMfHgBKTUVDnG2KcqIQsh9jHItqx/HdiFMGjdV76sU1DqkKgXDePMBHBRG9TrUm8YANf/2E6tHOXE7zY66c43L+cTl4dvo7JtdBpTpauZEI=
  - secure: VBWYv4yEHOezY2bGRe+Nptr+EIHtM8e7GYyFi36ZFjAwIvGsE66kd3CE+QaaXIwedV/CClSdxcWG04nP8yQBeLu9+xQG7mBcqdHtkHLRRRVbXOcX1jGzUHkzDnnet0XCcVPZt9fVeKczgyTIqbndOU4E61iqBK79WXU0S7oOXjI=
